name: Test for ENV

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    container: aosc/aosc-os-buildkit:latest

    steps:
      - uses: actions/github-script@v5
        id: get-head-sha
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })
            console.log(pr)
            return pr.head.sha
          result-encoding: string

      - name: Display ENV
        run: |
          echo Ref: $GITHUB_REF
          echo Head ref: $GITHUB_HEAD_REF
          echo Base ref: $GITHUB_BASE_REF
          echo PR: ${{ github.event.issue.number }}
      - name: Prepare for building the package
        working-directory: ${{env.GITHUB_WORKSPACE}}
        env:
          PR_NUMBER: ${{github.event.issue.number}}
        run: |
          git clone https://github.com/${{github.repository}} .
          git checkout ${{ steps.get-head-sha.outputs.result }}
          mkdir -p /var/lib/acbs
          ln -s $PWD /var/lib/acbs/repo
          sed -i 's/Null Packager <null@aosc.xyz>/GitHub Actions <discussions@lists.aosc.io>/' /etc/autobuild/ab3cfg.sh
